"""Create user and blog table migration

Revision ID: 032171815b52
Revises: 
Create Date: 2024-08-23 09:39:19.368988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032171815b52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
